//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFameworkPart3DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        public int TRANSACTION_ID { get; set; }
        public Nullable<decimal> TRANSACTION_AMOUNT { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
